name: Deploy Truray to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Create .env file
      run: |
        echo "${{ secrets.BACKEND_ENV }}" > .env
    
    - name: Deploy Backend
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "config,src,public,storage,.htaccess,.env,composer.json,database_schema.sql"
        target: "/home/${{ secrets.SSH_USER }}/domains/orange-ferret-922211.hostingersite.com/public_html/"
        overwrite: true
        
    - name: Fix Permissions
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /home/${{ secrets.SSH_USER }}/domains/orange-ferret-922211.hostingersite.com/public_html
          
          # Fix all permissions
          find . -type d -exec chmod 755 {} \;
          find . -type f -exec chmod 644 {} \;
          
          # Secure sensitive files
          chmod 600 .env 2>/dev/null || true
          
          # Writable directories
          mkdir -p storage/logs storage/uploads public/uploads
          chmod -R 775 storage public/uploads
          
          # Install dependencies
          composer install --no-dev --optimize-autoloader 2>/dev/null || echo "Composer not available"